categories:
- Graph/Display Data
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.7 of gview
name: package_gview_1_7
owner: ioa
remote_repository_url: https://github.com/pseudogene/galaxy/tree/master/packages/package_gview_1_7
type: tool_dependency_definition